### ISSUE TITLE
Calling disconnect() on async client sometimes results in Bunny\Exception\ClientException

### ISSUE THREAD

**Issue by ondrejmirtes** [jakubkulhan/bunny#12]
Bunny\Exception\ClientException: Received frame #1 on closed channel #1.

**Comment by jakubkulhan** [comment]
Unfortunately, there is no easy way to cleanly shutdown AMQP connection and at the same time process (ack) all delivered messages so far. So I opted to drop frames when connection/channel is being closed. If the consumer has to ack messages (consume not initiated with `noAck` option), clean shutdown of an connection will result in RabbitMQ (broker) delivering messages to the next consumer.

Can you confirm the fix works? (The code I used to reproduce the issue is in `AsyncClientTest:: testDisconnectWithBufferedMessages()` - https://github.com/jakubkulhan/bunny/blob/master/test/Bunny/AsyncClientTest.php#L158)

**Comment by ondrejmirtes** [comment]
Thank you very much, I will let you know if there are any more problems.
