### ISSUE TITLE
client unexpectedly closed TCP connection

### ISSUE THREAD

**Issue by sm2017** [jakubkulhan/bunny#58]
In rabbitmq logs I see too many `client unexpectedly closed TCP connection`

**Comment by jakubkulhan** [comment]
Hi! This happened to me when there was a load balancer between the clients and the broker with idle timeout lower than heartbeat.

Even if there is no LB, I guess this happens because of setting `heartbeat` timeout too low. [Default is 60 seconds.](https://github.com/jakubkulhan/bunny/blob/master/src/Bunny/AbstractClient.php#L132) If you do in consumers any work longer than that, the PHP cannot send heartbeat packet to the broker, therefore the connection gets closed.

**Comment by sm2017** [comment]
@jakubkulhan there is no load balancer and my heartbeat timeout is 60 seconds
I have no works longer that 5 seconds

**Comment by jakubkulhan** [comment]
Do you use sync, or async client? For sync client you have to call [`Client::run()`](https://github.com/jakubkulhan/bunny/blob/master/src/Bunny/Client.php#L171). Async client need to be passed React event loop and then event loop's `run()` method has to be called.

**Comment by jakubkulhan** [comment]
I don't see a reason why this happens. If it happens only after days of the consumer running, try checking if there are no memory leaks (cycles) that could cause long GC pauses.

**Comment by sm2017** [comment]
@jakubkulhan I see in rabbitmq logs that 0.5 second after connection is established . connection closed with `client unexpectedly closed TCP connection` error

**Comment by sm2017** [comment]
@jakubkulhan Do you know why the connection is closed after less that a seconds?
And rabbit mq server detect it is `client unexpectedly closed TCP connection` ?

**Comment by jakubkulhan** [comment]
Duplicated in #59

**Comment by iskripka** [comment]
@sm2017 did you manage to solve the problem with _client unexpectedly closed TCP connection_?

**Comment by sm2017** [comment]
@iskripka it's for years ago, I don't remember
